---
name: APC UPS Daemon
version: "2.2"
slug: apcupsd
description: View information from APC USB UPSs
url: https://github.com/chrisclayson/hassio-apcupsd/tree/main/apcupsd
startup: services
init: false
arch:
  - aarch64
image: "chrisclayson/hassio-apcupsd-{arch}"
ports:
  3551/tcp: 3551
ports_description:
  3551/tcp: APC daemon port (make empty to disable)
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
uart: true
usb: true
gpio: true
audio: false
apparmor: false
host_dbus: true
devices:
  - /dev:/dev:rwm
map:
  - share:rw
journald: true
options:
  name: "APC UPS"
  cable: "usb"
  type: "usb"
  device: ""
  extra: []
schema:
  name: str
  cable: str
  type: str
  device: str?
  extra:
    - key: str
      val: str
